Bump haml to potentially resolve an issue
We are getting this error in the log in staging, but not locally.

```
2025-05-04T23:37:12.893979+00:00 app[web.1]: E, [2025-05-04T23:37:12.893939 #28] ERROR -- : [a0f53c83-4069-4c01-a71b-7bae3369c04b]
2025-05-04T23:37:12.893980+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b] ActionView::Template::Error (undefined method `capture' for an instance of String):
2025-05-04T23:37:12.893981+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]
2025-05-04T23:37:12.893981+00:00 app[web.1]: Causes:
2025-05-04T23:37:12.893981+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b] NoMethodError (undefined method `capture' for an instance of String)
2025-05-04T23:37:12.893982+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     1: - numbers_page = NumbersPage.new
2025-05-04T23:37:12.893982+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     2:
2025-05-04T23:37:12.893982+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     3: - cache "numbers-fragment" do
2025-05-04T23:37:12.893983+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     4:   .typography.small-11.small-centered.medium-10.large-8
2025-05-04T23:37:12.893983+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     5:     %h1 Numbers
2025-05-04T23:37:12.893983+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]     6:     .clearfix_left.column-block
2025-05-04T23:37:12.893984+00:00 app[web.1]: [a0f53c83-4069-4c01-a71b-7bae3369c04b]
```

Its described here
https://github.com/rails/rails/issues/50401#issuecomment-2465424719

This PR is kinda hoping to fix it, but I don;t know if it will until its
deployed....